version: '3'

services:
  fact_bot:
    image: stepastrunkv/fact_bot

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10
