version: '3'

services:
  fact_bot:
    image: stepastrunkov/fact_bot
    environment:
        TOKEN: ${TOKEN}
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10
